### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pgserver==0.0.4

### ISSUE THREAD

**Issue by avinash-infinite** [pixeltable/pixeltable#110]
Hi Team,
I am trying to test some functionalities of pixeltable
while installing the library on python 3.9 or 3.11(tried both), I am getting the error as:

Code: !pip install pixeltable
  error: subprocess-exited-with-error
  Building wheel for hnswlib (pyproject.toml) did not run successfully.
 
  Code: !pip install git+https://github.com/mkornacker/pixeltable
 Error:
  Running command git clone --filter=blob:none --quiet https://github.com/mkornacker/pixeltable 'C:\Users\Abhishek\AppData\Local\Temp\pip-req-build-tyvk6y_2'
ERROR: Could not find a version that satisfies the requirement pgserver==0.0.4 (from pixeltable) (from versions: none)
ERROR: No matching distribution found for pgserver==0.0.4

Also, I am not able to find the requirements.txt file where I can manually omit pgserver to use rest of the functionality, Also I am not able to find pgserver library in pip, can you please help me with this?

Thanks,
Avinash

**Comment by aaron-siegel** [comment]
The documentation and pypi library are out of date. We're working on this now and expect to have a fix shortly (hopefully by EOD today). Apologies for the inconvenience.

Thanks!
Aaron

**Comment by aaron-siegel** [comment]
It appears that you're running Windows, correct? So that's the real problem (not stale docs/pypi): we haven't yet released a Pixeltable distribution for Windows. (pgserver is a core part of Pixeltable, so you won't be able to run any functionality without it.)

We're investigating releasing a Windows distribution but don't yet have an ETA on how long it will take. I'll keep this ticket updated.

Thanks!
Aaron

**Comment by aaron-siegel** [comment]
We just released Pixeltable v0.2.3, which has been tested to run properly on Windows. Can you try again to see if it installs on your system now?

Thanks!
Aaron

**Comment by aaron-siegel** [comment]
This is fixed as of v0.2.3.
